# [LAB 12] 3-2. 회귀분석 결과보고 모듈화

## #01. 준비작업

### 1. 패키지 참조

In [1]:
# 라이브러리 기본 참조
from jussam import load_data
from helpers import *
from IPython.display import display, Markdown

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [2]:
origin = load_data('cars')
origin.head()

📚 자동차의 속도(speed)에 따른 제동거리(dist) 조사 데이터 (출처: R 기본 데이터)

   speed  dist
0      4     2
1      4    10
2      7     4
3      7    22
4      8    16

### 3. 단순선형회귀

In [3]:
fit = my_ols.fit_model(origin, 'dist', summary=True)

                            OLS Regression Results
==============================================================================
Dep. Variable:                   dist   R-squared:                       0.651
Model:                            OLS   Adj. R-squared:                  0.644
Method:                 Least Squares   F-statistic:                     89.57
Date:                Thu, 23 Jul 2026   Prob (F-statistic):           1.49e-12
Time:                        07:44:02   Log-Likelihood:                -206.58
No. Observations:                  50   AIC:                             417.2
Df Residuals:                      48   BIC:                             421.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -17.5791      6.758     -2.601      0.012     -31.168      -3.990
speed          3.9324      0.416      9.464      0.000       3.097       4.768
==============================================================================
Omnibus:                        8.975   Durbin-Watson:                   1.676
Prob(Omnibus):                  0.011   Jarque-Bera (JB):                8.189
Skew:                           0.885   Prob(JB):                       0.0167
Kurtosis:                       3.893   Cond. No.                         50.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## #02. 모듈화 기능 확인

### 1. 회귀분석 결과 보고의 일괄 처리

In [4]:
# 회귀계수 표
vdf = my_ols.report_variables(fit, origin)
display(vdf)

# 모형적합도 보고 (로그변환 없음)
display(Markdown(my_ols.report_fitness(fit)))

# 독립변수 보고 (로그변환 없음)
display(Markdown(my_ols.report_variables_text(fit)))

   종속변수   독립변수     B  표준오차     β     t  유의확률    공차   VIF
0  dist  speed 3.932 0.416 0.807 9.464 0.000 1.000 1.000

**Note. n = 50. F(1, 48) = 89.57, p < 0.001, R² = 0.651, Adj.R² = 0.644, Durbin-Watson = 1.676**

dist를 종속변수로, speed(을)를 독립변수로한 단순선형회귀분석 결과, 모형은 통계적으로 유의하였다.

> F(1, 48) = 89.57, p < 0.001, R² = 0.651.

즉, speed는 dist의 약 65.11%를 설명하는 것으로 나타났다.

- **speed**의 회귀계수는 **B = 3.93**으로 나타났으며, 이는 **dist**에 유의한 요인임을 의미한다. (**t(48) = 9.46**, **p < .001**) 즉, speed가 **1 증가**할 때 dist는 평균적으로 **3.93 증가**하는 것으로 해석된다.