# [LAB-04] 9. 파생변수 - 연습문제

## 준비작업

### 라이브러리 참조

In [1]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 데이터 가져오기

In [2]:
df = load_data("online_shop_sales")
df

📚 우수 고객을 찾아라! - 영업 데이터 분석 챌린지

    field      description
--  ---------  ----------------
 0  OrderID    주문번호(인덱스)
 1  UserID     고객아이디
 2  Product    상품
 3  Price      가격
 4  Quantity   주문수량
 5  OrderDate  주문일

    UserID          Product  Price  Quantity  OrderDate
0     1001           Laptop   1200         1 2024-10-01
1     1002            Mouse     25         2 2024-10-01
2     1001         Keyboard     75         1 2024-10-02
3     1003          Monitor    300         1 2024-10-03
4     1002           Webcam     50         1 2024-10-04
5     1003       HDMI Cable     15         3 2024-10-05
6     1001          USB Hub     30         2 2024-10-06
7     1004           Laptop   1300         1 2024-10-07
8     1002            Mouse     25         1 2024-10-08
9     1003          Monitor    300         2 2024-10-09
10    1001     External SSD    150         1 2024-10-10
11    1004  Docking Station    250         1 2024-10-11
12    1002         Keyboard     80         1 2024-10-12
13    1003           Webcam     55         1 2024-10-13
14    1001            Mouse     28         1 2024-10-14

## 요구사항 해결

### 1. 고객별 총 주문 금액 구하기

In [3]:
df1 = df.copy()
df1["Total"] = df1["Price"] * df1["Quantity"]
df2 = df1.filter(["UserID", "Total"]).groupby("UserID").sum()
df2

        Total
UserID
1001     1513
1002      205
1003     1000
1004     1550

### 2. 총 주문 금액의 내림차순으로 상위 2명

In [4]:
df2.sort_values("Total", ascending=False).head(2)

        Total
UserID
1004     1550
1001     1513